name: Update dashboard

permissions:
  contents: write

on:
  schedule:
    - cron: '00 06 * * *'
  workflow_dispatch:

jobs:
  update-dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5
        with:
          path: main
      - name: Checkout gh-pages
        uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages
      - name: Download and process artifacts
        working-directory: ./main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
          node main
          git config --global user.name "GitHub Actions"
          git config --global user.email "username@users.noreply.github.com"
          git add data
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Add artifacts from Playwright's CI"
            git push
          fi
      - name: Publish dashboard
        working-directory: ./gh-pages
        run: |
          git add data.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update dashboard"
            git push
          fi
